import kudeGen from "./KUDEGen";
import fs from "fs";
import path from "path";

class QRGen {
  generateKUDE = async (
    java8Path: string,
    xmlSigned: string,
    urlLogo: string,
    ambiente: string
  ): Promise<Buffer> => {
    // Call generateKUDE - ambiente is the destination folder
    await kudeGen.generateKUDE(java8Path, xmlSigned, urlLogo, ambiente);
    
    // Find the generated PDF file in the destination folder
    // The PDF file name is typically based on the XML file name or generated by the Java process
    const destDir = ambiente;
    const files = fs.readdirSync(destDir);
    const pdfFile = files.find((file: string) => file.endsWith('.pdf'));
    
    if (!pdfFile) {
      throw new Error(`No PDF file found in destination folder: ${destDir}`);
    }
    
    const pdfPath = path.join(destDir, pdfFile);
    const fileBuffer = fs.readFileSync(pdfPath);
    
    return fileBuffer;
  };
}

export default new QRGen();
